from __future__ import annotations

from pathlib import Path

import click

from .converters.odt import PandocOdtConverter
from .converters.pdf import PandocLuaLatexPdfConverter, check_pdf_math_dependencies
from .converters.pdf_mathml_postprocessor import (
    extract_mathml_from_html,
    extract_mathml_from_latex_images,
    inject_mathml_into_figures,
    inject_mathml_into_pdf,
)
from .html_processor import HtmlProcessor
from .latex_extractor import extract_latex as _extract_latex
from .latex_extractor import write_csv
from .math.backends.latex2mathml_backend import Latex2MathMLBackend
from .math.backends.mathjax_backend import MathJaxNodeBackend
from .math.backends.sre_backend import SpeechConversionError, SreNodeBackend
from .prince_preprocessor import PrinceHtmlPreprocessor


@click.command()
@click.argument("input_path", type=click.Path(exists=True, path_type=Path))
@click.option("--format", "output_format", type=click.Choice(["html", "pdf", "odt"]), default="html", show_default=True)
@click.option("--output", "output_path", type=click.Path(path_type=Path), required=True)
@click.option(
    "--math-backend",
    type=click.Choice(["mathjax", "latex2mathml"]),
    default="mathjax",
    show_default=True,
)
@click.option(
    "--prince-preprocess",
    is_flag=True,
    default=False,
    help=(
        "Prepare the HTML output for Prince XML accessibility tagging.  "
        "Adds role=\"math\" to math elements so Prince tags them as Formula "
        "structure elements in the PDF, and copies xml:lang to lang on the "
        "root <html> element.  When combined with --spoken-alt-text, also "
        "replaces LaTeX alt text on math images with spoken descriptions "
        "(storing the original LaTeX in data-latex for downstream MathML "
        "conversion)."
    ),
)
@click.option(
    "--spoken-alt-text",
    is_flag=True,
    default=False,
    help=(
        "Replace the LaTeX source in math image alt attributes with plain-"
        "English spoken descriptions generated by Speech Rule Engine (SRE).  "
        "The original LaTeX is preserved in the title attribute.  "
        "Requires Node.js with the node/ dependencies installed."
    ),
)
@click.option(
    "--image-only",
    is_flag=True,
    default=False,
    help=(
        "Keep Pressbooks math images (``<img class='latex'>``) intact in the "
        "output HTML instead of converting them to ``<math>`` MathML elements.  "
        "Visual rendering remains pixel-perfect (Prince lays out the original "
        "images).  When combined with --prince-preprocess and --spoken-alt-text, "
        "the alt text on each image is still replaced with a spoken description.  "
        "Use pb-postprocess-pdf --html to attach MathML as Associated Files on "
        "the resulting Figure structure elements after Prince runs."
    ),
)
def main(
    input_path: Path,
    output_format: str,
    output_path: Path,
    math_backend: str,
    prince_preprocess: bool,
    spoken_alt_text: bool,
    image_only: bool,
) -> None:
    """Process a Pressbooks HTML export into HTML, PDF, or ODT."""
    sre_backend: SreNodeBackend | None = None
    if spoken_alt_text:
        sre_backend = SreNodeBackend()
        # Fail early with a clear message if Node.js / SRE is not available.
        try:
            sre_backend.to_speech("x", display=False)
        except SpeechConversionError as exc:
            raise click.ClickException(
                f"Speech Rule Engine is not available: {exc}\n"
                "Install Node.js and run: "
                "npm install --prefix src/pressbooks_export/math/backends/node"
            ) from exc

    if image_only:
        # Gentle pipeline: keep math images intact for visual fidelity.
        # Only run the Prince preprocessor (adds role="math", lang fix, spoken alt).
        processed_html = input_path.read_text(encoding="utf-8")
        if prince_preprocess:
            processed_html = PrinceHtmlPreprocessor(
                sre_backend=sre_backend if spoken_alt_text else None,
            ).process_html(processed_html)
    else:
        # Full MathML-substitution pipeline: convert images → <math> elements.
        processor = HtmlProcessor(
            backend=MathJaxNodeBackend() if math_backend == "mathjax" else Latex2MathMLBackend(),
            spoken_alt_text=spoken_alt_text,
            sre_backend=sre_backend,
        )
        processed_html = processor.process_file(input_path)

        if prince_preprocess:
            processed_html = PrinceHtmlPreprocessor(
                sre_backend=sre_backend if spoken_alt_text else None,
            ).process_html(processed_html)

    if output_format == "html":
        output_path.write_text(processed_html, encoding="utf-8")
        click.echo(f"Wrote processed HTML to {output_path}")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    temp_html = output_path.with_suffix(".processed.html")
    temp_html.write_text(processed_html, encoding="utf-8")

    if output_format == "pdf":
        check_pdf_math_dependencies(
            warn_fn=lambda msg: click.echo(msg, err=True),
        )
        PandocLuaLatexPdfConverter().convert_html(temp_html, output_path)

        # Post-process: inject MathML as Associated Files on Formula tags.
        # This ensures Formula structure elements have <math> content even
        # when luamml does not embed it automatically.
        mathml_strings = extract_mathml_from_html(processed_html)
        if mathml_strings:
            updated = inject_mathml_into_pdf(output_path, mathml_strings)
            if updated:
                click.echo(
                    f"Injected MathML into {updated} Formula element(s) in PDF.",
                    err=True,
                )
    else:
        PandocOdtConverter().convert_html(temp_html, output_path)

    click.echo(f"Wrote {output_format.upper()} output to {output_path}")


@click.command()
@click.argument("pdf_path", type=click.Path(exists=True, path_type=Path))
@click.option(
    "--output",
    "output_path",
    type=click.Path(path_type=Path),
    default=None,
    help="Output path for the modified PDF (default: overwrite the input file in place).",
)
@click.option(
    "--html",
    "html_path",
    type=click.Path(exists=True, path_type=Path),
    default=None,
    help=(
        "Path to the processed HTML file used to generate the PDF.  "
        "When the HTML contains ``<math>`` elements (MathML-substitution "
        "pipeline), MathML is attached as Associated Files on Formula "
        "structure elements.  When it contains ``<img class='latex'>`` "
        "images (gentle / image-only pipeline), MathML is generated from "
        "the LaTeX in each image's alt/data-latex attribute and attached "
        "to the Figure structure elements that Prince creates for those "
        "images."
    ),
)
def postprocess_pdf(pdf_path: Path, output_path: Path | None, html_path: Path | None) -> None:
    """Apply PDF/UA-2 post-processing fixes to a Prince-generated PDF.

    Sets ViewerPreferences/DisplayDocTitle and injects a pdfuaid:part=2 XMP
    declaration — the two metadata fixes that Prince XML does not emit
    automatically.

    When --html is supplied, also attaches MathML Associated Files to the
    math structure elements in the PDF.  The pipeline is detected
    automatically from the HTML content:

    \b
    * MathML-substitution pipeline (HTML has <math> elements) → MathML is
      attached to Formula structure elements.
    * Gentle / image-only pipeline (HTML has <img class="latex"> images) →
      MathML is generated from the LaTeX source and attached to Figure
      structure elements (because Prince tags images as Figure, not Formula).

    Requires pikepdf: pip install 'pressbooks-export-tools[pdf]'
    """
    try:
        from .converters.prince_pdf_postprocessor import postprocess_for_pdfua2
    except ImportError as exc:
        raise click.ClickException(
            f"pikepdf is required for PDF post-processing: {exc}\n"
            "Install with: pip install 'pressbooks-export-tools[pdf]'"
        ) from exc

    postprocess_for_pdfua2(pdf_path, output_path)
    target = output_path if output_path is not None else pdf_path

    if html_path is not None:
        processed_html = html_path.read_text(encoding="utf-8")

        # Detect pipeline from HTML content.
        mathml_strings = extract_mathml_from_html(processed_html)
        if mathml_strings:
            # MathML-substitution pipeline: attach to Formula elements.
            updated = inject_mathml_into_pdf(target, mathml_strings)
            if updated:
                click.echo(
                    f"Injected MathML into {updated} Formula element(s) in PDF.",
                    err=True,
                )
        else:
            # Gentle pipeline: generate MathML from latex images → Figure elements.
            image_mathml = extract_mathml_from_latex_images(processed_html)
            if image_mathml:
                updated = inject_mathml_into_figures(target, image_mathml)
                if updated:
                    click.echo(
                        f"Injected MathML into {updated} Figure element(s) in PDF.",
                        err=True,
                    )
            else:
                click.echo(
                    "No <math> elements or <img class='latex'> images found in the supplied HTML.",
                    err=True,
                )

    click.echo(f"PDF/UA-2 post-processing complete: {target}")


@click.command()
@click.argument("input_path", type=click.Path(exists=True, path_type=Path))
@click.option(
    "--output",
    "output_path",
    type=click.Path(path_type=Path),
    required=True,
    help="Path to the output CSV file.",
)
@click.option(
    "--classes",
    default="latex mathjax",
    show_default=True,
    help=(
        "Space-separated list of CSS class names an <img> element must have "
        "to be treated as a LaTeX equation."
    ),
)
def extract_latex(input_path: Path, output_path: Path, classes: str) -> None:
    """Extract LaTeX equations from INPUT_PATH and write them to a CSV.

    Each row in the CSV contains the LaTeX source, whether the equation is
    displayed as a block or inline, and a plain-English spoken description
    generated by Speech Rule Engine (SRE).

    Requires Node.js with the node/ dependencies installed
    (npm install --prefix src/pressbooks_export/math/backends/node).
    """
    classes_list = classes.split()
    if not classes_list:
        raise click.UsageError("--classes must contain at least one class name.")

    html_content = input_path.read_text(encoding="utf-8")

    backend = SreNodeBackend()

    # Fail early with a clear message if Node.js / SRE is not available.
    try:
        backend.to_speech("x", display=False)
    except SpeechConversionError as exc:
        raise click.ClickException(
            f"Speech Rule Engine is not available: {exc}\n"
            "Install Node.js and run: "
            "npm install --prefix src/pressbooks_export/math/backends/node"
        ) from exc

    entries = _extract_latex(html_content, classes=classes_list, sre_backend=backend)

    if not entries:
        click.echo(
            f"No LaTeX equations found (looking for <img> with classes: {classes_list}).",
            err=True,
        )

    write_csv(entries, output_path)
    click.echo(f"Wrote {len(entries)} equation(s) to {output_path}")
