from __future__ import annotations

from pathlib import Path

import click

from .converters.odt import PandocOdtConverter
from .converters.pdf import PandocLuaLatexPdfConverter, check_pdf_math_dependencies
from .converters.pdf_mathml_postprocessor import (
    extract_mathml_from_html,
    inject_mathml_into_pdf,
)
from .html_processor import HtmlProcessor
from .latex_extractor import extract_latex as _extract_latex
from .latex_extractor import write_csv
from .math.backends.latex2mathml_backend import Latex2MathMLBackend
from .math.backends.mathjax_backend import MathJaxNodeBackend
from .math.backends.sre_backend import SpeechConversionError, SreNodeBackend


@click.command()
@click.argument("input_path", type=click.Path(exists=True, path_type=Path))
@click.option("--format", "output_format", type=click.Choice(["html", "pdf", "odt"]), default="html", show_default=True)
@click.option("--output", "output_path", type=click.Path(path_type=Path), required=True)
@click.option(
    "--math-backend",
    type=click.Choice(["mathjax", "latex2mathml"]),
    default="mathjax",
    show_default=True,
)
def main(input_path: Path, output_format: str, output_path: Path, math_backend: str) -> None:
    """Process a Pressbooks HTML export into HTML, PDF, or ODT."""
    processor = HtmlProcessor(
        backend=MathJaxNodeBackend() if math_backend == "mathjax" else Latex2MathMLBackend()
    )
    processed_html = processor.process_file(input_path)

    if output_format == "html":
        output_path.write_text(processed_html, encoding="utf-8")
        click.echo(f"Wrote processed HTML to {output_path}")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    temp_html = output_path.with_suffix(".processed.html")
    temp_html.write_text(processed_html, encoding="utf-8")

    if output_format == "pdf":
        check_pdf_math_dependencies(
            warn_fn=lambda msg: click.echo(msg, err=True),
        )
        PandocLuaLatexPdfConverter().convert_html(temp_html, output_path)

        # Post-process: inject MathML as Associated Files on Formula tags.
        # This ensures Formula structure elements have <math> content even
        # when luamml does not embed it automatically.
        mathml_strings = extract_mathml_from_html(processed_html)
        if mathml_strings:
            updated = inject_mathml_into_pdf(output_path, mathml_strings)
            if updated:
                click.echo(
                    f"Injected MathML into {updated} Formula element(s) in PDF.",
                    err=True,
                )
    else:
        PandocOdtConverter().convert_html(temp_html, output_path)

    click.echo(f"Wrote {output_format.upper()} output to {output_path}")


@click.command()
@click.argument("input_path", type=click.Path(exists=True, path_type=Path))
@click.option(
    "--output",
    "output_path",
    type=click.Path(path_type=Path),
    required=True,
    help="Path to the output CSV file.",
)
@click.option(
    "--classes",
    default="latex mathjax",
    show_default=True,
    help=(
        "Space-separated list of CSS class names an <img> element must have "
        "to be treated as a LaTeX equation."
    ),
)
def extract_latex(input_path: Path, output_path: Path, classes: str) -> None:
    """Extract LaTeX equations from INPUT_PATH and write them to a CSV.

    Each row in the CSV contains the LaTeX source, whether the equation is
    displayed as a block or inline, and a plain-English spoken description
    generated by Speech Rule Engine (SRE).

    Requires Node.js with the node/ dependencies installed
    (npm install --prefix src/pressbooks_export/math/backends/node).
    """
    classes_list = classes.split()
    if not classes_list:
        raise click.UsageError("--classes must contain at least one class name.")

    html_content = input_path.read_text(encoding="utf-8")

    backend = SreNodeBackend()

    # Fail early with a clear message if Node.js / SRE is not available.
    try:
        backend.to_speech("x", display=False)
    except SpeechConversionError as exc:
        raise click.ClickException(
            f"Speech Rule Engine is not available: {exc}\n"
            "Install Node.js and run: "
            "npm install --prefix src/pressbooks_export/math/backends/node"
        ) from exc

    entries = _extract_latex(html_content, classes=classes_list, sre_backend=backend)

    if not entries:
        click.echo(
            f"No LaTeX equations found (looking for <img> with classes: {classes_list}).",
            err=True,
        )

    write_csv(entries, output_path)
    click.echo(f"Wrote {len(entries)} equation(s) to {output_path}")
