from __future__ import annotations

import logging
from pathlib import Path

from lxml import html

from .math.backends.base import MathBackend
from .math.backends.sre_backend import SpeechConversionError, SreNodeBackend
from .math.detector import LatexImage, find_latex_images
from .math.substituter import replace_latex_images

logger = logging.getLogger(__name__)


class HtmlProcessor:
    """Convert exported Pressbooks math placeholders into MathML.

    Parameters
    ----------
    backend:
        Math conversion backend (MathJax or latex2mathml).
    spoken_alt_text:
        When *True*, replace the LaTeX source in each math image's ``alt``
        attribute with a plain-English spoken description generated by Speech
        Rule Engine.  The original LaTeX is preserved in the ``title``
        attribute (Pressbooks already populates ``title`` with the LaTeX, so
        no information is lost).  Requires Node.js and the SRE package; see
        :class:`~pressbooks_export.math.backends.sre_backend.SreNodeBackend`.
    sre_backend:
        Speech Rule Engine backend used when *spoken_alt_text* is *True*.
        A default :class:`SreNodeBackend` is constructed when *None*.  Pass
        an explicit instance to customise the Node binary / script path or to
        inject a test double.
    """

    def __init__(
        self,
        backend: MathBackend,
        *,
        spoken_alt_text: bool = False,
        sre_backend: SreNodeBackend | None = None,
    ) -> None:
        self.backend = backend
        self.spoken_alt_text = spoken_alt_text
        self._sre_backend: SreNodeBackend | None = sre_backend

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def process_html(self, markup: str) -> str:
        """Return *markup* with math images replaced and optional spoken alt text."""
        document = html.fromstring(markup)
        latex_images = find_latex_images(document)
        speeches = self._collect_speeches(latex_images) if self.spoken_alt_text else None
        replace_latex_images(document, latex_images, self.backend, speeches=speeches)
        return html.tostring(document, encoding="unicode", pretty_print=True)

    def process_file(self, path: Path) -> str:
        """Read *path* and return the processed HTML string."""
        return self.process_html(path.read_text(encoding="utf-8"))

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _get_sre_backend(self) -> SreNodeBackend:
        if self._sre_backend is None:
            self._sre_backend = SreNodeBackend()
        return self._sre_backend

    def _collect_speeches(self, latex_images: list[LatexImage]) -> list[str] | None:
        """Return a list of spoken descriptions for *latex_images*, or *None* on failure.

        Uses :class:`SreNodeBackend` to convert each LaTeX expression to a
        plain-English description in a single Node.js subprocess call.
        Returns *None* (and logs a warning) if SRE is unavailable or the batch
        conversion fails, allowing the caller to skip ``aria-label`` injection
        gracefully.
        """
        if not latex_images:
            return None

        sre = self._get_sre_backend()
        items = [(img.latex, img.display) for img in latex_images]

        try:
            return sre.to_speech_batch(items)
        except SpeechConversionError as exc:
            logger.warning(
                "spoken-alt-text: SRE batch conversion failed, aria-label not set: %s",
                exc,
            )
            return None
